window.CHECKLIST = [
  {
    id: "week",
    title: "0 · Do this week",
    items: [
      { id: "fso-notify", text: "Clay: notify FSO / security officer ASAP (before the week of travel)", priority: true },
      { id: "fso-itinerary", text: "Submit full itinerary: cities, dates, flights, hotels, purpose", priority: true },
      { id: "fso-companion", text: "List travel companion (Tom — citizenship, relationship)" },
      { id: "fso-passport", text: "Confirm passport number + travel dates in their system" },
      { id: "fso-briefing", text: "Ask if you need a pre-travel / CI defensive briefing" },
      { id: "fso-confirm", text: "Save confirmation / case number" },
      { id: "fso-return", text: "After return: report changes + weird contacts within ~5 business days" },
      { id: "passports-valid", text: "Both passports valid through at least Sept 11, 2026 (6+ months safer)", priority: true },
      { id: "passport-photo", text: "Photo of passport bio page in phone + cloud" },
      { id: "names-match", text: "Confirm names on tickets match passports exactly" },
    ],
  },
  {
    id: "entry",
    title: "1 · Entry / country notifications",
    items: [
      { id: "jp-visa", text: "Japan: no tourist visa needed (≤90 days) — noted", done: true },
      { id: "jp-jesta", text: "Japan: no JESTA yet in 2026 — not required", done: true },
      { id: "jp-vjw", text: "Optional: Visit Japan Web QR before landing", href: "https://www.vjw.digital.go.jp/", priority: true },
      { id: "kr-visa", text: "Korea: no tourist visa for ≤90 days — noted", done: true },
      { id: "kr-keta", text: "Korea: K-ETA not required for US through Dec 31, 2026 — confirm closer to travel", href: "https://www.k-eta.go.kr/" },
      { id: "kr-earrival", text: "File Korea e-Arrival Card ≤3 days before landing", href: "https://www.e-arrivalcard.go.kr/", priority: true },
      { id: "kr-address", text: "Have Seoul hostel address ready for the form" },
      { id: "us-step", text: "Optional: enroll in STEP for Japan + Korea", href: "https://step.state.gov/" },
      { id: "embassy", text: "Save Tokyo / Seoul embassy contacts offline" },
    ],
  },
  {
    id: "bookings",
    title: "2 · Book stays & flights",
    items: [
      { id: "stay-tokyo", text: "Tokyo Aug 28–31 — The Millennials Shibuya (alt: UNPLAN Shinjuku)", priority: true },
      { id: "stay-osaka", text: "Osaka Aug 31–Sept 2 — iloha Namba (alt: White Hostel)", priority: true },
      { id: "stay-kyoto", text: "Kyoto Sept 2–7 — Ritz-Carlton points/NUA + confirmation PDF", priority: true },
      { id: "stay-seoul", text: "Seoul Sept 7–10 — Time Travelers Hongdae (alt: Zzzip)", priority: true },
      { id: "stay-haneda", text: "Haneda night Sept 10 — plat hostel keikyu haneda home", priority: true },
      { id: "fly-kix-icn", text: "Book Osaka (KIX/ITM) → ICN ~Sept 7 morning/midday", priority: true },
      { id: "fly-icn-hnd", text: "Book ICN → HND ~Sept 10 afternoon/evening", priority: true },
      { id: "boarding-shots", text: "Screenshot boarding passes / PNRs into shared album" },
      { id: "clay-flights", text: "Clay UA803 IAD→HND / NH102 HND→IAD (PNR FJGI5Z)", done: true },
      { id: "tom-flights", text: "Tom UA79 outbound / UA78 NRT→EWR", done: true },
    ],
  },
  {
    id: "experiences",
    title: "3 · Experiences & dinners",
    items: [
      { id: "shibuya-sky", text: "Shibuya Sky timed ticket — Aug 29", priority: true },
      { id: "teamlab", text: "teamLab Planets timed ticket — Aug 30", priority: true },
      { id: "tokyo-yakiniku", text: "Tokyo yakiniku dinner — Aug 29 (TableCheck / Jojoen)" },
      { id: "osaka-dinner", text: "Osaka nicer dinner — Sept 1" },
      { id: "pontocho", text: "Kyoto Pontocho dinner — Sept 2" },
      { id: "kyoto-nice", text: "Kyoto nice dinner — Sept 5 (Ritz concierge)" },
      { id: "shinkansen", text: "Shinkansen seats Tokyo→Osaka — Aug 31 (SmartEX)", priority: true },
      { id: "haruka", text: "Optional: Haruka reserved seats Kyoto→KIX — Sept 7" },
    ],
  },
  {
    id: "money",
    title: "4 · Money, phones, apps",
    items: [
      { id: "banks", text: "Tell banks / Amex / Chase you’re in JP + KR" },
      { id: "no-fx-fee", text: "Confirm cards that don’t foreign-tx fees" },
      { id: "atm-plan", text: "ATM plan: 7-Eleven (JP) · convenience stores (KR)" },
      { id: "esim", text: "eSIM or pocket Wi‑Fi — decide + order", priority: true },
      { id: "unlock", text: "Unlock phones if needed" },
      { id: "app-maps", text: "Apps: Google Maps" },
      { id: "app-naver", text: "Apps: Naver Map + KakaoMap (Korea)" },
      { id: "app-papago", text: "Apps: Papago" },
      { id: "app-kakao-t", text: "Apps: Kakao T (Korea taxi)" },
      { id: "app-table", text: "Apps: TableCheck / Tabelog" },
      { id: "app-airlines", text: "Apps: United / ANA" },
      { id: "app-hostels", text: "HostelWorld / booking confirmations offline" },
      { id: "suica", text: "Japan transit: Suica/Pasmo (Wallet or airport)" },
      { id: "tmoney", text: "Korea transit: T-money (CU/GS25 or ICN)" },
    ],
  },
  {
    id: "health",
    title: "5 · Health / insurance / docs",
    items: [
      { id: "insurance", text: "Travel insurance — share policy # with Tom", priority: true },
      { id: "rx", text: "Prescriptions in original bottles + photo of Rx" },
      { id: "yakkan", text: "Check Japan med restrictions / Yakkan Shoumei if needed" },
      { id: "kit", text: "Basic kit: ibuprofen, Imodium, band-aids, electrolytes" },
      { id: "vaccines", text: "Vaccine status current (confirm with doctor if needed)" },
    ],
  },
  {
    id: "packing",
    title: "6 · Packing",
    items: [
      { id: "shoes", text: "Destroyable walking shoes" },
      { id: "teamlab-clothes", text: "Clothes OK for teamLab water areas" },
      { id: "nice-outfit", text: "One nicer outfit (Ritz / Pontocho)" },
      { id: "rain", text: "Light rain layer" },
      { id: "flops", text: "Flip-flops (jjimjilbang / hostel showers)" },
      { id: "battery", text: "Portable battery + cable(s)" },
      { id: "adapter", text: "Universal adapter (JP Type A 100V · KR Type C/F 220V)" },
      { id: "earplugs", text: "Earplugs + eye mask" },
      { id: "daypack", text: "Small daypack" },
      { id: "docs-cloud", text: "Cloud folder: passports, flights, hotels, insurance, FSO confirmation" },
    ],
  },
  {
    id: "ops",
    title: "7 · Shared ops",
    items: [
      { id: "shared-album", text: "Shared album / doc: PNRs, addresses, Ritz, emergency contacts" },
      { id: "split", text: "Agree split method (Splitwise / Venmo by city)" },
      { id: "cash", text: "Who carries backup cash (~$200–300 each to start)" },
      { id: "offline-maps", text: "Exchange WhatsApp / iMessage + offline maps for neighborhoods" },
      { id: "sept11", text: "Sept 11: Clay HND morning · Tom transfer to NRT — exact train plan" },
    ],
  },
  {
    id: "final72",
    title: "8 · Final 72 hours",
    items: [
      { id: "checkin", text: "Online check-in windows set (UA / ANA)" },
      { id: "vjw-done", text: "Visit Japan Web QR completed", priority: true },
      { id: "earrival-done", text: "Korea e-Arrival Card submitted", priority: true },
      { id: "offline-gmaps", text: "Download offline Maps for Tokyo / Osaka / Kyoto / Seoul" },
      { id: "charge-packs", text: "Charge battery packs" },
      { id: "taxi-notes", text: "Hostel addresses in Notes (JP/KR text for taxi drivers)" },
      { id: "fso-reconfirm", text: "Re-confirm FSO travel report matches final itinerary" },
    ],
  },
];
